### ISSUE TITLE
SMplayer opens an extra window when starting to play - WTH?

### ISSUE THREAD

**Issue by GrafDogi** [smplayer-dev/smplayer#827]
**Describe the bug**
All of a sudden(!) SMPlayer arbitrarily opens an extra mpv window when starting to play a video file.
Often it comes on the first time a video file is played, but sometimes it shows up when playing a video file for the 2nd, 3rd or 4th time.
That is REALLY annoying as I don't want an extra window at all AND the keyboard controls won't work on that extra window.

**To Reproduce**
Double click a new video file. No matter the extension. Either it shows up or not. It shows up 7/10 video files.

**Expected behavior**
No extra window at all. Just like before!

**Screenshots**
![github_Screenshot 2023-11-04 135113](https://github.com/smplayer-dev/smplayer/assets/60138900/5242a46e-f1d0-4237-9435-15bc35a6ff1a)

After starting that same file for the 3rd time:
![github_2_Screenshot 2023-11-04 135150](https://github.com/smplayer-dev/smplayer/assets/60138900/bbb00eb2-1108-4752-b5fb-13980bff06ad)

**Your Enviroment**
 - SMPlayer version: 21.10.0 rev10000
 - OS: Win10 21H2 b19044.3086
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X] MPV

**Logs**

[smplayer_log.txt](https://github.com/smplayer-dev/smplayer/files/13256701/smplayer_log.txt)

Why does the extra window occur so haphazardly?
What can I do to prevent the extra window from showing?

**Comment by smplayer-dev** [comment]
What video output is selected in preferences -> general -> video?

**Comment by GrafDogi** [comment]
![image](https://github.com/smplayer-dev/smplayer/assets/60138900/989eb4ca-4b2b-47e8-956b-cd37ade007b4)
I think that's "standard". I've reset the settings while installing the newest version bc I thought resetting or updating it would resolve the problem. :-(

**Comment by smplayer-dev** [comment]
It's strange, but unfortunatelly I can't reproduce this problem in my computer.
Please send the smplayer log after playing a file with this problem.

**Comment by GrafDogi** [comment]
Believe it or not... I can't reproduce it either any more :-(
Darn....! I tested up to 10 videos. They all played inside the SMPlayer GUI :-( Sorry for the commotion.

I will provide the logs when that problem occurs again :)

**Comment by hnsteyding** [comment]
Maybe you select accidentally these setting ?
![grafik](https://github.com/smplayer-dev/smplayer/assets/65712636/2c82170c-4191-444a-89b7-c7e64e723368)

**Comment by GrafDogi** [comment]
I am afraid I am not able to check on that bc I've setup my PC again, and that problem is gone.
But I will keep an eye on that checkbox! 
Thank you!

**Comment by DisasterArea96** [comment]
I ham experiencing something similar - it started occurring after I moved over to wayland from x11 on debian 12 with kde plasma.

Judging by the author of the issue using Windows this issue might not be OS-specific

Edit: For me, switching back to x11 fixed the issue. That doesn't solve the OP's issue but hopefully it provides some useful information?

**Comment by smplayer-dev** [comment]
> I ham experiencing something similar - it started occurring after I moved over to wayland from x11 on debian 12 with kde plasma.
> 

What version of SMPlayer are you using? I thought that problem was fixed in version 23.6.

**Comment by DisasterArea96** [comment]
> > I ham experiencing something similar - it started occurring after I moved over to wayland from x11 on debian 12 with kde plasma.
> 
> What version of SMPlayer are you using? I thought that problem was fixed in version 23.6.

Ah - I am only on 22.7.0! When I get a chance I'll upgrade to 23.6 or later. It looks like I downloaded it via the KDE Discover App, so it may be that the version on there needs to be updated too?

Edit: In the Discover App it says it was distributed by unofficial_media_packages-stable-main

**Comment by smplayer-dev** [comment]
There's a package for debian 12 here:
https://software.opensuse.org/download.html?project=home%3Asmplayerdev&package=smplayer

**Comment by Piroro-hs** [comment]
Well, I have exactly the same issue on Wayland. SMPlayer is latest (23.12).

**Comment by DisasterArea96** [comment]
> Well, I have exactly the same issue on Wayland. SMPlayer is latest (23.12).

I have just retried with the latest appimage version as well as updating from the openSUSE download page. I am still experiencing this issue! (using either method)

**Comment by smplayer-dev** [comment]
When using an appimage package, be sure to select "mpv" from the comboxbox. Don't use /usr/bin/mpv or something like that. That's to be sure the smplayer uses the mpv version included in the package instead of the mpv in your system.
